import Footer from "@/components/layout/Footer";
import Navbarserver from "@/components/layout/Navbarserver";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Providers from '../components/providerReactQuery';
import { ThemeProvider } from "../components/ThemeProvider";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers >
        <SessionProvider>
        <ThemeProvider>
         <Navbarserver/>
          {children}
          <Toaster position="top-right" />
         <Footer/>
          </ThemeProvider>
          </SessionProvider>
          </Providers>
      </body>
    </html>
  );
}
